// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ytm.proto

package com.bihu.singledevice.push;

@SuppressWarnings("all")
public final class Ytm {
  private Ytm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *type奇数是c-&gt;s 偶数是s-&gt;c
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    boolean hasHeartConnect();
    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    com.bihu.singledevice.push.Ytm.HeartConnect getHeartConnect();
    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder getHeartConnectOrBuilder();

    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    boolean hasSendInstruct();
    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    com.bihu.singledevice.push.Ytm.SendInstruct getSendInstruct();
    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    com.bihu.singledevice.push.Ytm.SendInstructOrBuilder getSendInstructOrBuilder();
  }
  /**
   * Protobuf type {@code ClientMessage}
   */
  public  static final class ClientMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientMessage)
      ClientMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientMessage() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.bihu.singledevice.push.Ytm.HeartConnect.Builder subBuilder = null;
              if (heartConnect_ != null) {
                subBuilder = heartConnect_.toBuilder();
              }
              heartConnect_ = input.readMessage(com.bihu.singledevice.push.Ytm.HeartConnect.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartConnect_);
                heartConnect_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.bihu.singledevice.push.Ytm.SendInstruct.Builder subBuilder = null;
              if (sendInstruct_ != null) {
                subBuilder = sendInstruct_.toBuilder();
              }
              sendInstruct_ = input.readMessage(com.bihu.singledevice.push.Ytm.SendInstruct.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sendInstruct_);
                sendInstruct_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bihu.singledevice.push.Ytm.internal_static_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bihu.singledevice.push.Ytm.internal_static_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bihu.singledevice.push.Ytm.ClientMessage.class, com.bihu.singledevice.push.Ytm.ClientMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *type奇数是c-&gt;s 偶数是s-&gt;c
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int HEARTCONNECT_FIELD_NUMBER = 2;
    private com.bihu.singledevice.push.Ytm.HeartConnect heartConnect_;
    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    public boolean hasHeartConnect() {
      return heartConnect_ != null;
    }
    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    public com.bihu.singledevice.push.Ytm.HeartConnect getHeartConnect() {
      return heartConnect_ == null ? com.bihu.singledevice.push.Ytm.HeartConnect.getDefaultInstance() : heartConnect_;
    }
    /**
     * <pre>
     * 心跳包协议
     * </pre>
     *
     * <code>.HeartConnect heartConnect = 2;</code>
     */
    public com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder getHeartConnectOrBuilder() {
      return getHeartConnect();
    }

    public static final int SENDINSTRUCT_FIELD_NUMBER = 3;
    private com.bihu.singledevice.push.Ytm.SendInstruct sendInstruct_;
    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    public boolean hasSendInstruct() {
      return sendInstruct_ != null;
    }
    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    public com.bihu.singledevice.push.Ytm.SendInstruct getSendInstruct() {
      return sendInstruct_ == null ? com.bihu.singledevice.push.Ytm.SendInstruct.getDefaultInstance() : sendInstruct_;
    }
    /**
     * <pre>
     *发送指令
     * </pre>
     *
     * <code>.SendInstruct sendInstruct = 3;</code>
     */
    public com.bihu.singledevice.push.Ytm.SendInstructOrBuilder getSendInstructOrBuilder() {
      return getSendInstruct();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (heartConnect_ != null) {
        output.writeMessage(2, getHeartConnect());
      }
      if (sendInstruct_ != null) {
        output.writeMessage(3, getSendInstruct());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (heartConnect_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeartConnect());
      }
      if (sendInstruct_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSendInstruct());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bihu.singledevice.push.Ytm.ClientMessage)) {
        return super.equals(obj);
      }
      com.bihu.singledevice.push.Ytm.ClientMessage other = (com.bihu.singledevice.push.Ytm.ClientMessage) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && (hasHeartConnect() == other.hasHeartConnect());
      if (hasHeartConnect()) {
        result = result && getHeartConnect()
            .equals(other.getHeartConnect());
      }
      result = result && (hasSendInstruct() == other.hasSendInstruct());
      if (hasSendInstruct()) {
        result = result && getSendInstruct()
            .equals(other.getSendInstruct());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      if (hasHeartConnect()) {
        hash = (37 * hash) + HEARTCONNECT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartConnect().hashCode();
      }
      if (hasSendInstruct()) {
        hash = (37 * hash) + SENDINSTRUCT_FIELD_NUMBER;
        hash = (53 * hash) + getSendInstruct().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bihu.singledevice.push.Ytm.ClientMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientMessage)
        com.bihu.singledevice.push.Ytm.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bihu.singledevice.push.Ytm.internal_static_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bihu.singledevice.push.Ytm.internal_static_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bihu.singledevice.push.Ytm.ClientMessage.class, com.bihu.singledevice.push.Ytm.ClientMessage.Builder.class);
      }

      // Construct using com.bihu.singledevice.push.Ytm.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (heartConnectBuilder_ == null) {
          heartConnect_ = null;
        } else {
          heartConnect_ = null;
          heartConnectBuilder_ = null;
        }
        if (sendInstructBuilder_ == null) {
          sendInstruct_ = null;
        } else {
          sendInstruct_ = null;
          sendInstructBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bihu.singledevice.push.Ytm.internal_static_ClientMessage_descriptor;
      }

      public com.bihu.singledevice.push.Ytm.ClientMessage getDefaultInstanceForType() {
        return com.bihu.singledevice.push.Ytm.ClientMessage.getDefaultInstance();
      }

      public com.bihu.singledevice.push.Ytm.ClientMessage build() {
        com.bihu.singledevice.push.Ytm.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bihu.singledevice.push.Ytm.ClientMessage buildPartial() {
        com.bihu.singledevice.push.Ytm.ClientMessage result = new com.bihu.singledevice.push.Ytm.ClientMessage(this);
        result.type_ = type_;
        if (heartConnectBuilder_ == null) {
          result.heartConnect_ = heartConnect_;
        } else {
          result.heartConnect_ = heartConnectBuilder_.build();
        }
        if (sendInstructBuilder_ == null) {
          result.sendInstruct_ = sendInstruct_;
        } else {
          result.sendInstruct_ = sendInstructBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bihu.singledevice.push.Ytm.ClientMessage) {
          return mergeFrom((com.bihu.singledevice.push.Ytm.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bihu.singledevice.push.Ytm.ClientMessage other) {
        if (other == com.bihu.singledevice.push.Ytm.ClientMessage.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.hasHeartConnect()) {
          mergeHeartConnect(other.getHeartConnect());
        }
        if (other.hasSendInstruct()) {
          mergeSendInstruct(other.getSendInstruct());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bihu.singledevice.push.Ytm.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bihu.singledevice.push.Ytm.ClientMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *type奇数是c-&gt;s 偶数是s-&gt;c
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *type奇数是c-&gt;s 偶数是s-&gt;c
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *type奇数是c-&gt;s 偶数是s-&gt;c
       * </pre>
       *
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.bihu.singledevice.push.Ytm.HeartConnect heartConnect_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bihu.singledevice.push.Ytm.HeartConnect, com.bihu.singledevice.push.Ytm.HeartConnect.Builder, com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder> heartConnectBuilder_;
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public boolean hasHeartConnect() {
        return heartConnectBuilder_ != null || heartConnect_ != null;
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public com.bihu.singledevice.push.Ytm.HeartConnect getHeartConnect() {
        if (heartConnectBuilder_ == null) {
          return heartConnect_ == null ? com.bihu.singledevice.push.Ytm.HeartConnect.getDefaultInstance() : heartConnect_;
        } else {
          return heartConnectBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public Builder setHeartConnect(com.bihu.singledevice.push.Ytm.HeartConnect value) {
        if (heartConnectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartConnect_ = value;
          onChanged();
        } else {
          heartConnectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public Builder setHeartConnect(
          com.bihu.singledevice.push.Ytm.HeartConnect.Builder builderForValue) {
        if (heartConnectBuilder_ == null) {
          heartConnect_ = builderForValue.build();
          onChanged();
        } else {
          heartConnectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public Builder mergeHeartConnect(com.bihu.singledevice.push.Ytm.HeartConnect value) {
        if (heartConnectBuilder_ == null) {
          if (heartConnect_ != null) {
            heartConnect_ =
              com.bihu.singledevice.push.Ytm.HeartConnect.newBuilder(heartConnect_).mergeFrom(value).buildPartial();
          } else {
            heartConnect_ = value;
          }
          onChanged();
        } else {
          heartConnectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public Builder clearHeartConnect() {
        if (heartConnectBuilder_ == null) {
          heartConnect_ = null;
          onChanged();
        } else {
          heartConnect_ = null;
          heartConnectBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public com.bihu.singledevice.push.Ytm.HeartConnect.Builder getHeartConnectBuilder() {
        
        onChanged();
        return getHeartConnectFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      public com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder getHeartConnectOrBuilder() {
        if (heartConnectBuilder_ != null) {
          return heartConnectBuilder_.getMessageOrBuilder();
        } else {
          return heartConnect_ == null ?
              com.bihu.singledevice.push.Ytm.HeartConnect.getDefaultInstance() : heartConnect_;
        }
      }
      /**
       * <pre>
       * 心跳包协议
       * </pre>
       *
       * <code>.HeartConnect heartConnect = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bihu.singledevice.push.Ytm.HeartConnect, com.bihu.singledevice.push.Ytm.HeartConnect.Builder, com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder> 
          getHeartConnectFieldBuilder() {
        if (heartConnectBuilder_ == null) {
          heartConnectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bihu.singledevice.push.Ytm.HeartConnect, com.bihu.singledevice.push.Ytm.HeartConnect.Builder, com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder>(
                  getHeartConnect(),
                  getParentForChildren(),
                  isClean());
          heartConnect_ = null;
        }
        return heartConnectBuilder_;
      }

      private com.bihu.singledevice.push.Ytm.SendInstruct sendInstruct_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bihu.singledevice.push.Ytm.SendInstruct, com.bihu.singledevice.push.Ytm.SendInstruct.Builder, com.bihu.singledevice.push.Ytm.SendInstructOrBuilder> sendInstructBuilder_;
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public boolean hasSendInstruct() {
        return sendInstructBuilder_ != null || sendInstruct_ != null;
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public com.bihu.singledevice.push.Ytm.SendInstruct getSendInstruct() {
        if (sendInstructBuilder_ == null) {
          return sendInstruct_ == null ? com.bihu.singledevice.push.Ytm.SendInstruct.getDefaultInstance() : sendInstruct_;
        } else {
          return sendInstructBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public Builder setSendInstruct(com.bihu.singledevice.push.Ytm.SendInstruct value) {
        if (sendInstructBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendInstruct_ = value;
          onChanged();
        } else {
          sendInstructBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public Builder setSendInstruct(
          com.bihu.singledevice.push.Ytm.SendInstruct.Builder builderForValue) {
        if (sendInstructBuilder_ == null) {
          sendInstruct_ = builderForValue.build();
          onChanged();
        } else {
          sendInstructBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public Builder mergeSendInstruct(com.bihu.singledevice.push.Ytm.SendInstruct value) {
        if (sendInstructBuilder_ == null) {
          if (sendInstruct_ != null) {
            sendInstruct_ =
              com.bihu.singledevice.push.Ytm.SendInstruct.newBuilder(sendInstruct_).mergeFrom(value).buildPartial();
          } else {
            sendInstruct_ = value;
          }
          onChanged();
        } else {
          sendInstructBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public Builder clearSendInstruct() {
        if (sendInstructBuilder_ == null) {
          sendInstruct_ = null;
          onChanged();
        } else {
          sendInstruct_ = null;
          sendInstructBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public com.bihu.singledevice.push.Ytm.SendInstruct.Builder getSendInstructBuilder() {
        
        onChanged();
        return getSendInstructFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      public com.bihu.singledevice.push.Ytm.SendInstructOrBuilder getSendInstructOrBuilder() {
        if (sendInstructBuilder_ != null) {
          return sendInstructBuilder_.getMessageOrBuilder();
        } else {
          return sendInstruct_ == null ?
              com.bihu.singledevice.push.Ytm.SendInstruct.getDefaultInstance() : sendInstruct_;
        }
      }
      /**
       * <pre>
       *发送指令
       * </pre>
       *
       * <code>.SendInstruct sendInstruct = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bihu.singledevice.push.Ytm.SendInstruct, com.bihu.singledevice.push.Ytm.SendInstruct.Builder, com.bihu.singledevice.push.Ytm.SendInstructOrBuilder> 
          getSendInstructFieldBuilder() {
        if (sendInstructBuilder_ == null) {
          sendInstructBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bihu.singledevice.push.Ytm.SendInstruct, com.bihu.singledevice.push.Ytm.SendInstruct.Builder, com.bihu.singledevice.push.Ytm.SendInstructOrBuilder>(
                  getSendInstruct(),
                  getParentForChildren(),
                  isClean());
          sendInstruct_ = null;
        }
        return sendInstructBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientMessage)
    }

    // @@protoc_insertion_point(class_scope:ClientMessage)
    private static final com.bihu.singledevice.push.Ytm.ClientMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bihu.singledevice.push.Ytm.ClientMessage();
    }

    public static com.bihu.singledevice.push.Ytm.ClientMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    public com.bihu.singledevice.push.Ytm.ClientMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartConnectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartConnect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *心跳设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    java.lang.String getDeviceid();
    /**
     * <pre>
     *心跳设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceidBytes();
  }
  /**
   * Protobuf type {@code HeartConnect}
   */
  public  static final class HeartConnect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartConnect)
      HeartConnectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartConnect.newBuilder() to construct.
    private HeartConnect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartConnect() {
      deviceid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartConnect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bihu.singledevice.push.Ytm.internal_static_HeartConnect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bihu.singledevice.push.Ytm.internal_static_HeartConnect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bihu.singledevice.push.Ytm.HeartConnect.class, com.bihu.singledevice.push.Ytm.HeartConnect.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceid_;
    /**
     * <pre>
     *心跳设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    public java.lang.String getDeviceid() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *心跳设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceidBytes() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bihu.singledevice.push.Ytm.HeartConnect)) {
        return super.equals(obj);
      }
      com.bihu.singledevice.push.Ytm.HeartConnect other = (com.bihu.singledevice.push.Ytm.HeartConnect) obj;

      boolean result = true;
      result = result && getDeviceid()
          .equals(other.getDeviceid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.HeartConnect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bihu.singledevice.push.Ytm.HeartConnect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartConnect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartConnect)
        com.bihu.singledevice.push.Ytm.HeartConnectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bihu.singledevice.push.Ytm.internal_static_HeartConnect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bihu.singledevice.push.Ytm.internal_static_HeartConnect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bihu.singledevice.push.Ytm.HeartConnect.class, com.bihu.singledevice.push.Ytm.HeartConnect.Builder.class);
      }

      // Construct using com.bihu.singledevice.push.Ytm.HeartConnect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bihu.singledevice.push.Ytm.internal_static_HeartConnect_descriptor;
      }

      public com.bihu.singledevice.push.Ytm.HeartConnect getDefaultInstanceForType() {
        return com.bihu.singledevice.push.Ytm.HeartConnect.getDefaultInstance();
      }

      public com.bihu.singledevice.push.Ytm.HeartConnect build() {
        com.bihu.singledevice.push.Ytm.HeartConnect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bihu.singledevice.push.Ytm.HeartConnect buildPartial() {
        com.bihu.singledevice.push.Ytm.HeartConnect result = new com.bihu.singledevice.push.Ytm.HeartConnect(this);
        result.deviceid_ = deviceid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bihu.singledevice.push.Ytm.HeartConnect) {
          return mergeFrom((com.bihu.singledevice.push.Ytm.HeartConnect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bihu.singledevice.push.Ytm.HeartConnect other) {
        if (other == com.bihu.singledevice.push.Ytm.HeartConnect.getDefaultInstance()) return this;
        if (!other.getDeviceid().isEmpty()) {
          deviceid_ = other.deviceid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bihu.singledevice.push.Ytm.HeartConnect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bihu.singledevice.push.Ytm.HeartConnect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceid_ = "";
      /**
       * <pre>
       *心跳设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public java.lang.String getDeviceid() {
        java.lang.Object ref = deviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *心跳设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceidBytes() {
        java.lang.Object ref = deviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *心跳设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *心跳设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder clearDeviceid() {
        
        deviceid_ = getDefaultInstance().getDeviceid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *心跳设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartConnect)
    }

    // @@protoc_insertion_point(class_scope:HeartConnect)
    private static final com.bihu.singledevice.push.Ytm.HeartConnect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bihu.singledevice.push.Ytm.HeartConnect();
    }

    public static com.bihu.singledevice.push.Ytm.HeartConnect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartConnect>
        PARSER = new com.google.protobuf.AbstractParser<HeartConnect>() {
      public HeartConnect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartConnect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartConnect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartConnect> getParserForType() {
      return PARSER;
    }

    public com.bihu.singledevice.push.Ytm.HeartConnect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendInstructOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SendInstruct)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    java.lang.String getDeviceid();
    /**
     * <pre>
     *设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceidBytes();

    /**
     * <pre>
     *指令内容
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     *指令内容
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code SendInstruct}
   */
  public  static final class SendInstruct extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SendInstruct)
      SendInstructOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendInstruct.newBuilder() to construct.
    private SendInstruct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendInstruct() {
      deviceid_ = "";
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendInstruct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bihu.singledevice.push.Ytm.internal_static_SendInstruct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bihu.singledevice.push.Ytm.internal_static_SendInstruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bihu.singledevice.push.Ytm.SendInstruct.class, com.bihu.singledevice.push.Ytm.SendInstruct.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceid_;
    /**
     * <pre>
     *设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    public java.lang.String getDeviceid() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *设备ID
     * </pre>
     *
     * <code>string deviceid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceidBytes() {
      java.lang.Object ref = deviceid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     *指令内容
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *指令内容
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceid_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceid_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bihu.singledevice.push.Ytm.SendInstruct)) {
        return super.equals(obj);
      }
      com.bihu.singledevice.push.Ytm.SendInstruct other = (com.bihu.singledevice.push.Ytm.SendInstruct) obj;

      boolean result = true;
      result = result && getDeviceid()
          .equals(other.getDeviceid());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceid().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bihu.singledevice.push.Ytm.SendInstruct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bihu.singledevice.push.Ytm.SendInstruct prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SendInstruct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SendInstruct)
        com.bihu.singledevice.push.Ytm.SendInstructOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bihu.singledevice.push.Ytm.internal_static_SendInstruct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bihu.singledevice.push.Ytm.internal_static_SendInstruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bihu.singledevice.push.Ytm.SendInstruct.class, com.bihu.singledevice.push.Ytm.SendInstruct.Builder.class);
      }

      // Construct using com.bihu.singledevice.push.Ytm.SendInstruct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceid_ = "";

        data_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bihu.singledevice.push.Ytm.internal_static_SendInstruct_descriptor;
      }

      public com.bihu.singledevice.push.Ytm.SendInstruct getDefaultInstanceForType() {
        return com.bihu.singledevice.push.Ytm.SendInstruct.getDefaultInstance();
      }

      public com.bihu.singledevice.push.Ytm.SendInstruct build() {
        com.bihu.singledevice.push.Ytm.SendInstruct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bihu.singledevice.push.Ytm.SendInstruct buildPartial() {
        com.bihu.singledevice.push.Ytm.SendInstruct result = new com.bihu.singledevice.push.Ytm.SendInstruct(this);
        result.deviceid_ = deviceid_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bihu.singledevice.push.Ytm.SendInstruct) {
          return mergeFrom((com.bihu.singledevice.push.Ytm.SendInstruct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bihu.singledevice.push.Ytm.SendInstruct other) {
        if (other == com.bihu.singledevice.push.Ytm.SendInstruct.getDefaultInstance()) return this;
        if (!other.getDeviceid().isEmpty()) {
          deviceid_ = other.deviceid_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bihu.singledevice.push.Ytm.SendInstruct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bihu.singledevice.push.Ytm.SendInstruct) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceid_ = "";
      /**
       * <pre>
       *设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public java.lang.String getDeviceid() {
        java.lang.Object ref = deviceid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceidBytes() {
        java.lang.Object ref = deviceid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder clearDeviceid() {
        
        deviceid_ = getDefaultInstance().getDeviceid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备ID
       * </pre>
       *
       * <code>string deviceid = 1;</code>
       */
      public Builder setDeviceidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       *指令内容
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *指令内容
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *指令内容
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令内容
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令内容
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SendInstruct)
    }

    // @@protoc_insertion_point(class_scope:SendInstruct)
    private static final com.bihu.singledevice.push.Ytm.SendInstruct DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bihu.singledevice.push.Ytm.SendInstruct();
    }

    public static com.bihu.singledevice.push.Ytm.SendInstruct getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendInstruct>
        PARSER = new com.google.protobuf.AbstractParser<SendInstruct>() {
      public SendInstruct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendInstruct(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendInstruct> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendInstruct> getParserForType() {
      return PARSER;
    }

    public com.bihu.singledevice.push.Ytm.SendInstruct getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartConnect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartConnect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendInstruct_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendInstruct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tytm.proto\"g\n\rClientMessage\022\014\n\004type\030\001 \001" +
      "(\005\022#\n\014heartConnect\030\002 \001(\0132\r.HeartConnect\022" +
      "#\n\014sendInstruct\030\003 \001(\0132\r.SendInstruct\" \n\014" +
      "HeartConnect\022\020\n\010deviceid\030\001 \001(\t\".\n\014SendIn" +
      "struct\022\020\n\010deviceid\030\001 \001(\t\022\014\n\004data\030\002 \001(\tB\034" +
      "\n\032com.bihu.singledevice.pushb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMessage_descriptor,
        new java.lang.String[] { "Type", "HeartConnect", "SendInstruct", });
    internal_static_HeartConnect_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartConnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartConnect_descriptor,
        new java.lang.String[] { "Deviceid", });
    internal_static_SendInstruct_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SendInstruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendInstruct_descriptor,
        new java.lang.String[] { "Deviceid", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
