SET(CMAKE_SYSTEM_NAME "Generic")
SET(CMAKE_SYSTEM_PROCESSOR "STM32")

SET(TOOLCHAIN_DIR "/opt/ARM_HOME/gcc-arm-none-eabi")

SET(TOOLCHAIN_SIZE "${TOOLCHAIN_DIR}/bin/arm-none-eabi-size")
SET(TOOLCHAIN_OBJCOPY "${TOOLCHAIN_DIR}/bin/arm-none-eabi-objcopy")

SET(CMAKE_C_COMPILER "${TOOLCHAIN_DIR}/bin/arm-none-eabi-gcc")
SET(CMAKE_CXX_COMPILER "${TOOLCHAIN_DIR}/bin/arm-none-eabi-g++")

SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(CMAKE_EXE_LINKER_FLAGS "--specs=nosys.specs" CACHE INTERNAL "")
